### ISSUE TITLE
Add some DSA questions with separate folders.

### ISSUE THREAD

**Issue by durgesh2001** [durgesh2001/Hacktoberfest_2022#11]
You should add some codes related to different **DSA problems** with proper comments.

**Comment by deep-poharkar** [comment]
i would like to contribute.

**Comment by lognoroy** [comment]
I want to contribute.Can you please give me a chance?

**Comment by durgesh2001** [comment]
assigned.

**Comment by gagan-gv** [comment]
I would like to contribute

**Comment by lognoroy** [comment]
> assigned.

thanks for assigning me,
@durgesh2001 
I added insertion sort in cpp , Please Check and Merge.

**Comment by manishtambe** [comment]
@durgesh2001 i love to contribute few DSA problems can you assign this issue to me ?
