### ISSUE TITLE
Add a C++ folder for common sorting algorithms

### ISSUE THREAD

**Issue by aditya-464** [durgesh2001/Hacktoberfest_2022#15]
### @durgesh2001 Please assign this issue to me under "hacktoberfest" and "hacktoberfest-accepted" labels

**Comment by durgesh2001** [comment]
assigned.Start contributing.

**Comment by Aditi192002** [comment]
Please assign this to me

**Comment by RishabhSharma96** [comment]
@durgesh2001 Please assign this issue to me.
