### ISSUE TITLE
Glassmorphic Animated Calculator

### ISSUE THREAD

**Issue by RajAdwaita** [durgesh2001/Hacktoberfest_2022#39]
Project title
Glassmorphic Basic Calculator

Project Description
It will be a simple calculator with tilting effect and glassmorphic effect
Stack:

 Html
 CSS
 JavaScript

**Comment by durgesh2001** [comment]
Assigned. Add your code

**Comment by avijain09** [comment]
Please assign me this issue @durgesh2001 .
