### ISSUE TITLE
Movie Based Website

### ISSUE THREAD

**Issue by RajAdwaita** [durgesh2001/Hacktoberfest_2022#40]
A movie based website using html css and a bit of AI ML concept used to predict the success rate of the movie.

**Comment by RajAdwaita** [comment]
https://affectionate-nobel-ac0fee.netlify.app/

**Comment by durgesh2001** [comment]
Asssigned. Contribute yourself

**Comment by RajAdwaita** [comment]
Sure

**Comment by RajAdwaita** [comment]
@durgesh2001 pr initiated
